books/urls.py
from django.urls import path
from .views import *

app_name='books'
urlpatterns = [
    path('',HomeView.as_view(),name='home'),
    path('authors/',AuthorListView.as_view(),name='authors'),
    path('authors/<int:pk>/',AuthorDetailView.as_view(),name='author'),
    path('author/create/',AuthorCreateView.as_view(),name='author_create'),
    path('authors/edit/book/<int:pk>/',AuthorBooksEditView.as_view(),name='author_edit_book')
]

core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('books.urls',namespace='books')),
]

books/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

#!Author
class Author(models.Model):
    name = models.CharField(null=False,blank=False,max_length=255)
    last_name = models.CharField(null=True,blank=False,max_length=255)
    
    def get_absolute_url(self):
        print('Working get_absolute_url method at this class Author')
        return reverse('books:author',kwargs={'pk':self.pk})
    
    def __str__(self):
        return str(self.name)
    
#!Book
class Book(models.Model):
    title = models.CharField(null=False,blank=False,max_length=255)
    author = models.ForeignKey(Author,null=False,blank=False,on_delete=models.CASCADE,related_name='authorbook')
    
    def __str__(self):
        return f"{self.title} - {self.author}"
    
    

books/forms.py
from django.forms.models import inlineformset_factory
from .models import *

#!AuthorBooksFormset
AuthorBooksFormset = inlineformset_factory(Author,Book,fields=('title',),extra=1)

books/views.py
#!Django Methods
from django.shortcuts import render,redirect,HttpResponseRedirect
from django.urls import reverse,reverse_lazy
from django.contrib import messages
from django.views.generic.detail import SingleObjectMixin
from django.views.generic import TemplateView,ListView,CreateView,DetailView,FormView

#Django models and forms
from .models import *
from .forms import *

# Create your views here.
#!HomeView
class HomeView(TemplateView):
    template_name = 'books/home.html'

#!AuthorListView
class AuthorListView(ListView):#return= => object_list variable if not defined context_object_name in ListView
    model = Author
    context_object_name = 'authors'#if not define context_object_name in ListView,you define => modelname_list or object_list
    template_name = 'books/authors.html'

#!AuthorDetailView
class AuthorDetailView(DetailView):#return => object variable if not defined context_object_name in DetailView 
    model = Author
    context_object_name = 'author'
    template_name = 'books/author_detail.html'

#!AuthorCreateView
class AuthorCreateView(CreateView):
    model = Author
    fields = ['name','last_name']
    context_object_name = 'form'
    #success_url = reverse_lazy('books:authors')#when created Author,then redirect to this url vie reverse_lazy methods or used #! get_absolute_url
    template_name = 'books/author_create.html'
    
    def form_valid(self,form):
        messages.add_message(self.request,messages.SUCCESS,'The author has been added successfully')
        return super(AuthorCreateView,self).form_valid(form)#sending form overridinfv form_valid function

    def get_success_url(self):# or used success_url keyword and combile reverse_lazy keyword
        print('works get_success_url when created author')
        print('returned pk value for created author ', self.object.pk)
        return reverse('books:author',kwargs={'pk':self.object.pk})#if used function based view,adding redirect keyword before this code
    

#!AuthorBooksEditView
class AuthorBooksEditView(SingleObjectMixin,FormView):#Provide the ability to retrieve a single object for further manipulation.
    model = Author
    context_object_name = 'author'
    template_name = 'books/author_edit_book.html'
    
    def get(self,request,*args,**kwargs):
        print('Working get method at AuthorBooksEditView')
        self.object = self.get_object(queryset=Author.objects.all())#Return the object the view is displaying.
        print('self.object value at GET ', self.object.pk)#Find Author match to pk value automatically => For Example => Tolstoy
        print('------------------------------------------------')
        return super(AuthorBooksEditView,self).get(request,*args,**kwargs)
    
    def post(self,request,*args,**kwargs):
        print('Working post method at AuthorBooksEditView')
        self.object = self.get_object(queryset=Author.objects.all())
        print('self.object value at POST ', self.object)
        print('------------------------------------------------')
        return super(AuthorBooksEditView,self).post(request,*args,**kwargs)

    def get_form(self,form_class=None):
        print('working get_form')
        print('**self.get_form_kwargs() ', self.get_form_kwargs())
        print('self.object value at POST', self.object)
        print('------------------------------------------------')
        return AuthorBooksFormset(**self.get_form_kwargs(),instance=self.object)

    def form_valid(self,form):
        print('Working form_valid function')
        print('self.object value at FORM', self.object)
        print('------------------------------------------------')
        form.save()
        messages.add_message(self.request,messages.SUCCESS,'Changes were saved')
        return HttpResponseRedirect(self.get_success_url())
    
    def get_success_url(self):
        print('self.object value at SUCCESS_URL ', self.object)
        return reverse('books:author',kwargs={'pk':self.object.pk})

books/templates/books/author_create.html
{% extends "base.html" %}

{% block title %} Auhor Create {% endblock title %}

{% block content %}
    <form action="{% url 'books:author_create' %}" method="POST">
        {% for hidden_field in form.hidden_fields %}<!-- !This example does not handle any errors in the hidden fields. Usually, an error in a hidden field is a sign of form tampering, since normal form interaction won’t alter them.  -->
            {{hidden_field.errors}}
            {{hidden_field}}
        {% endfor %}

        {% csrf_token %}

        {{form.non_form_errors}}<!-- !Non-form errors will be rendered with an additional class of nonform to help distinguish them from form-specific errors. -->


        <!-- {{form}} => return all columns in table,stored one list -->

        {% for field in form %}<!-- iterate at form column each row an show html -->
            <!-- {{field.name}}  => return form_fields_name -->
            {{field.errors}}
            {{field.label_tag}} &nbsp; {{field}}
        {% endfor %}

        <p class="pt-2">
            <button type="submit" class="btn btn-warning w-100 mb-3 border rounded shadow-sm">Add An Author</button>
            <a href="{% url 'books:home' %}" role="button" class="btn btn-danger w-100 border rounded shadow-sm">Cancel</a>
        </p>

    </form>
{% endblock content %}

books/templates/books/author_detail.html
{% extends "base.html" %}

{% block title %} Author Detail {% endblock title %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                <strong>{{message}}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}

    <h3>Author Book Details</h3>
    <div class="d-flex d-flex-inline"><span class="pe-2">Authors name :&nbsp;</span><h5 class="text-muted">{{author.name|title}}</h5></div>
    <hr>
    {% for book in author.authorbook.all %}
        <div class="shadow border rounded p-4">
            <div class="small">Id : {{book.id}}</div>
            <div>Title : {{book.title}}</div>
        </div>
        <hr>
    {% endfor %}
    <p>
        <a href="{% url 'books:author_edit_book' author.pk %}" role="button" sclass="btn btn-primary w-100 mb-2">Edit Authors Books</a>
        <a href="{% url 'books:authors' %}" role="button" class="btn btn-secondary w-100">All Authors</a>
    </p>

{% endblock content %}

books/templates/books/author_edit_book.html
{% extends "base.html" %}

{% block title %} Editing books for {{author.name}} {% endblock title %}

{% block content %}
    <form action="{% url 'books:author_edit_book' author.pk %}" method="POST" enctype="multipart/form-data">
        {% for hidden_field in form.hidden_fields %}
            {{hidden_field.errors}}
            {{hidden_field}}<!-- !This example does not handle any errors in the hidden fields. Usually, an error in a hidden field is a sign of form tampering, since normal form interaction won’t alter them.  -->
        {% endfor %}

        {% csrf_token %}
        
        {{form.management_form}}<!-- !ManagementForm form is used by the formset to manage the collection of forms contained in the formset. -->
        {{form.non_form_errors}}<!-- !Non-form errors will be rendered with an additional class of nonform to help distinguish them from form-specific errors. -->
        
        <h3>Update Collection</h3>
        {% for book_form in form.forms %}<!-- ~BookForm bound=False, valid=Unknown, fields=(title;id;DELETE;author)> -->
            <hr>
            <h5>
                {% if book_form.instance.id %}
                    Book : {{book_form.instance.title|title}}
                {% else %}
                    {% if form.forms|length > 1 %}
                        Add another book
                    {% else %}
                        Add a book
                    {% endif %}
                {% endif %}
            </h5>
                {% for hidden_field in book_form.hidden_fields %}
                    {{hidden_field.errors}}
                {% endfor %}
            <table>
                {{book_form.as_table}}
            </table>
        {% endfor %}
        <hr>        
        <p>
            <button type="submit" value="Update Collection" class="btn btn-primary w-100 mb-3">Update Collection</button>
            <a href="{{author.get_absolute_url}}" role="button" class="btn btn-secondary w-100">Cancel</a>
        </p>

    </form>
{% endblock content %}

books/templates/books/authors.html
{% extends "base.html" %}

{% block title %} Authors {% endblock title %}

{% block content %}
    <h1 class="h3 text-dark fw-bold border border-secondary border-2 rounded p-3">Authors</h1>
    {% if authors %}
        <ul class="list-group">
            {% for author in authors %}
                <li class="list-group-item">
                    <a href="{% url 'books:author' author.pk %}" class="text-reset">{{author.name}}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <div class="alert alert-danger">
            <p>There are no author to display</p>
        </div>
    {% endif %}

    <p class="pt-2">
        <a href="{% url 'books:home' %}" role="button" class="btn btn-danger w-100">Cancel</a>
    </p>

{% endblock content %}

books/templates/books/home.html
{% extends "base.html" %}

{% block title %} Home {% endblock title %}

{% block content %}

    <h3 class="h3 text-muted fw-bold border border-secondary border-2 rounded p-3 mb-3">BookStore Collections</h3>
    <a href="{% url 'books:authors' %}" role="button" class="btn btn-primary w-100 mb-2">All Authors</a>
    <a href="{% url 'books:author_create' %}" role="button" class="btn btn-warning w-100">Add An Author</a>
{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en-us">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <title>{% block title %} Inline FormSet | {% endblock %}</title>
</head>

<body>
    <main>
        <div class="container-fluid">
            <div class="d-flex align-items-center py-5">
                <div class="col-12 col-md-6 col-lg-4 mx-auto">
                    {% block content %}
                    {% endblock content %}
                </div>
            </div>
        </div>
    </main>
</body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</html>